on: [push]

name: Tests

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install root project dependencies
        run: yarn
      - name: Install sample project dependencies
        run: yarn
        working-directory: ./sample
      - name: Run tests
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: yarn --cwd ./sample test
